### ISSUE TITLE
Users inadvertently separate Emperor files

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/emperor#424]
Currently, Emperor creates a single `.html` file and a folder of associated assets for rendering the plot.

People frequently separate these required assets leading to general confusion. Some ways these files can be separated:
- Emailing a collaborator the `index.html` file and not the folder.
- Downloading the `index.html` file and not the folder from a cloud service like dropbox, github, etc.
- From a `.zip` file, only the `index.html` file is extracted.

**How can we reduce confusion and prevent people from inadvertently separating these files?**

One option would be to use a web container format.
MHTML is one format, though it lacks native browser support...
[wiki on MHTML including browser support](https://en.wikipedia.org/wiki/MHTML)
[python program for building MHTML files](https://github.com/Modified/MHTifier)

Another option is data URLs, which has [much better browser support](http://caniuse.com/#feat=datauri). 
[python script to incode files into data URLs](https://gist.github.com/zacharyvoase/5538178)

**Comment by ElDeveloper** [comment]
This make sense! A self-contained format would be the best thing (I think), though we absolutely need it to be compatible with as many browsers as possible (even though we only really support Chrome) and that it can still be used as a web-resource from any website.

I think the main reason why this is a problem, is because when users separate the `emperor_required_resources` folder from the rest of their plot, they get a screen that among many other things says "WebGL" is not enabled, and this happens because the logic in index.html is no longer valid when the JS code is not available.

**Comment by colinbrislawn** [comment]
:+1: for cross browser support. Data URLs are the best option for that. I wonder which parts would need data URLs and what parts could be hard coded into that one HTML file...

**Comment by antgonza** [comment]
I think everything should be embedded (hardcoded), otherwise you will need Internet access to see plots ...

**Comment by colinbrislawn** [comment]
Agreed. Data URLs would let us do that for the images.

```
$ find emperor_required_resources | grep -c 'ico$'
1
$ find emperor_required_resources | grep -c 'png$'
17
$ find emperor_required_resources | grep -c 'css$'
9
$ find emperor_required_resources | grep -c 'js$'
26
```
The image files would need to be embedded using data URLs. It would not be too hard to hand code all the CSS and javascript, although that would effectively break the current compartmentalized design.

**Comment by squirrelo** [comment]
Fixed in the PR referenced above. Now looks like this if missing resources:

<img width="608" alt="screen shot 2016-05-16 at 15 32 17" src="https://cloud.githubusercontent.com/assets/3079066/15305956/76e63e40-1b7b-11e6-9020-3b9e834b6708.png">

**Comment by colinbrislawn** [comment]
Hey what's the status of this in the newest version of Emperor? Looks like some folks are [still having this problem,](https://groups.google.com/d/msg/qiime-forum/U0EOJ46ER10/BKdgwwjSCwAJ) but that just might be an older version that comes with qiime 1.9.1.

I'm still excited for our single-file-future! :shipit:

**Comment by ElDeveloper** [comment]
@colinbrislawn, since we won't be supporting QIIME 1.9.1 beginning January 1st, 2018, I think this will remain unsolved in QIIME 1.x. This however is **"**fixed**"** in the latest version of Emperor, the one that ships with QIIME2 since visualizations are delivered through qzv files, so it's harder for people to separate the data. 👍

**Comment by colinbrislawn** [comment]
Awesome! Go team. 👍
